config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :proponents, path: 'proponentes', path_names: { new: "novo", edit: "editar" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/proponents/calculate_discount', to: 'proponents#calculate_discount'
  post '/proponents/cities_by_state', to: 'proponents#cities_by_state'

  root to: 'proponents#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :city

  validates :public_place, :number, :neighborhood, :cep, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :proponent

  ##### CONSTANTS
  OWN = { id: 1, description: "Pessoal" }
  OTHER = { id: 2, description: "Referência" }
  KINDS = [ OWN, OTHER ]

  def self.get_human_kinds(kind)
    KINDS.each do |k|
      if kind == k[:id]
        return k[:description]
      end
    end
  end

end

app/models/proponent.rb
class Proponent < ApplicationRecord
  belongs_to :address
  has_many :telephones, class_name: 'Telephone', dependent: :destroy
  
  accepts_nested_attributes_for :telephones, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true

  ##### VALIDATIONS
  validates :name, :cpf, :date_birth, :salary, :discount, presence: true

  ##### CONSTANTS
  FIRST_RANGE = { min: nil, max: 1045, aliquot: 0.075 }
  SECOND_RANGE = { min: 1045.00, max: 2089.60, aliquot: 0.09 }
  THIRD_RANGE = { min: 2089.60, max: 3134.40, aliquot: 0.12 }
  FOURTH_RANGE = { min: 3134.40, max: 6101.06, aliquot: 0.14 }
  RANGES = [
    { range: 1, aliquot: (FIRST_RANGE[:max] * FIRST_RANGE[:aliquot]).truncate(2) },
    { range: 2, aliquot: ((SECOND_RANGE[:max] - SECOND_RANGE[:min]) * SECOND_RANGE[:aliquot]).truncate(2) },
    { range: 3, aliquot: ((THIRD_RANGE[:max] - THIRD_RANGE[:min]) * THIRD_RANGE[:aliquot]).truncate(2) },
    { range: 4, aliquot: ((FOURTH_RANGE[:max] - FOURTH_RANGE[:min]) * FOURTH_RANGE[:aliquot]).truncate(2) }
  ]

  def salary=(value)
    write_attribute :salary, value.gsub(/\./, '').gsub(/\,/, '.').to_d
  end

  def discount=(value)
    write_attribute :discount, value.gsub(/\./, '').gsub(/\,/, '.').to_d
  end

end

app/models/state.rb
class State < ApplicationRecord
end

app/models/telephone.rb
class Telephone < Contact
  ##### VALIDATIONS
  validates :value, :kind, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  before_action :set_proponent, only: [:show, :edit, :update, :destroy]
  
  def calculate_discount
    salary = params[:proponent][:salary].gsub(/[.,]/, '.' => '', ',' => '.').to_d

    if ( salary <= Proponent::FIRST_RANGE[:max] )
      discount = apply_aliquot(1, salary)
    elsif ( salary > Proponent::SECOND_RANGE[:min] && salary <= Proponent::SECOND_RANGE[:max] )
      discount = apply_aliquot(2, salary)
    elsif ( salary > Proponent::THIRD_RANGE[:min] && salary <= Proponent::THIRD_RANGE[:max] )
      discount = apply_aliquot(3, salary)
    elsif ( salary > Proponent::FOURTH_RANGE[:min] && salary <= Proponent::FOURTH_RANGE[:max] )
      discount = apply_aliquot(4, salary)
    end

    render json: { discount: discount.truncate(2) }
  end

  def cities_by_state
    render json: { cities: City.select(:name, :id).where(state_id: params[:proponent][:state]).order(:name) }
  end

  def index
    @proponents = Proponent.all
  end

  def show
  end

  def new
    @proponent = Proponent.new
    @proponent.build_address
  end

  def edit
    @state = @proponent.address.city.state.id
  end
  
  def create
    @proponent = Proponent.new(proponent_params)
    
    if @proponent.save
      redirect_to @proponent, notice: t('controllers.proponents.created')
    else
      @state = params[:state]
      render :new
    end
  end
  
  def update
    if @proponent.update(proponent_params)
      redirect_to @proponent, notice: t('controllers.proponents.updated')
    else
      @state = params[:state]
      render :edit
    end
  end

  def destroy
    @proponent.destroy
      redirect_to proponents_url, notice: t('controllers.proponents.destroyed')
  end

  private
    def set_proponent
      @proponent = Proponent.find(params[:id])
    end

    def proponent_params
      params.require(:proponent).permit(:address_id, :name, :cpf, :date_birth, :salary, :discount,
        address_attributes: [:id, :public_place, :city_id, :number, :neighborhood, :cep],
        telephones_attributes: [:id, :value, :other, :kind, :_destroy])
    end

    def apply_aliquot(range, salary)
      case range
        when 1
          discount = Proponent::RANGES.map{|r| r[:aliquot] if r[:range] == 1}.compact.sum
        when 2
          discount = ((salary - Proponent::SECOND_RANGE[:min]) * Proponent::SECOND_RANGE[:aliquot]).truncate(2)
          discount += Proponent::RANGES.map{|r| r[:aliquot] if r[:range] < 2}.compact.sum
        when 3
          discount = ((salary - Proponent::THIRD_RANGE[:min]) * Proponent::THIRD_RANGE[:aliquot]).truncate(2)
          discount += Proponent::RANGES.map{|r| r[:aliquot] if r[:range] < 3}.compact.sum
        when 4
          discount = ((salary - Proponent::FOURTH_RANGE[:min]) * Proponent::FOURTH_RANGE[:aliquot]).truncate(2)
          discount += Proponent::RANGES.map{|r| r[:aliquot] if r[:range] < 4}.compact.sum
      end
  
      return discount
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary border-bottom">
  <button class="btn btn-sm btn-outline-light" id="menu-toggle">
    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-list" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
    </svg>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <strong><%= current_user.email %></strong>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Editar perfil', edit_user_registration_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "Sair", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desconto INSS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex" id="wrapper">
      <% if user_signed_in? %>
        <div class="bg-light" id="sidebar-wrapper">
          <div class="sidebar-heading bg-primary text-light">Desconto INSS</div>
          <div class="list-group list-group-flush">
            <%= link_to "Proponentes", proponents_path, class: "list-group-item list-group-item-action bg-light" %>
            <%= link_to "Novo Proponente", new_proponent_path, class: "list-group-item list-group-item-action bg-light" %>
          </div>
        </div>
      <% end %>

      <div id="page-content-wrapper">
        <% if user_signed_in? %>
          <%= render 'layouts/header' %>
        <% end %>

          <% if notice %>
            <div class=" js-alert p-4">
              <div class="alert alert-success"><%= notice %></div>
            </div>
          <% end %>
          <% if alert %>
            <div class="js-alert p-4">
              <div class="alert alert-danger"><%= alert %></div>
            </div>
          <% end %>

        <div class="container-fluid p-4">
          <%= yield %>
        </div>

      </div>
    </div>

    <script>
      $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
      });

      $(".js-alert").fadeTo(2000, 500).slideUp(500, function() {
        $(".js-alert").slideUp(500);
      });
    </script>
  </body>
</html>

app/views/proponents/_address_fields.html.erb
<div class="nested-fields">
  <div class="form-row">
    <div class="col-4">
      <div class="form-group">
        <%= f.label :state  %>
        <%= select_tag :state, options_for_select(State.pluck(:name, :id), selected: @state), prompt: "Selecione", class: "form-control form-control-sm js-selectState" %>
      </div>
    </div>

    <div class="col-4">
      <div class="form-group">
        <%= f.label :city_id  %>
        <%= f.select :city_id, options_for_select(City.where(state_id: @state).pluck(:name, :id), selected: f.object.city_id), { include_blank: "Selecione" }, class: "form-control form-control-sm js-selectCity" %>
      </div>
    </div>

    <div class="col-4">
      <div class="form-group">
        <%= f.label :cep %>
        <%= f.text_field :cep, class: "form-control form-control-sm", data: { mask: "cep" }, maxlength: 10 %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="col-8">
      <div class="form-group">
        <%= f.label :public_place %>
        <%= f.text_field :public_place, class: "form-control form-control-sm" %>
      </div>
    </div>

    <div class="col-4">
      <div class="form-group">
        <%= f.label :number %>
        <%= f.text_field :number, class: "form-control form-control-sm" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="col-12">
      <div class="form-group">
        <%= f.label :neighborhood %>
        <%= f.text_field :neighborhood, class: "form-control form-control-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/proponents/_form.html.erb
<%= form_with(model: proponent, local: true) do |form| %>
  <% if proponent.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div class="d-sm-flex align-items-center">
        <svg width="2.0625em" height="2em" viewBox="0 0 17 16" class="bi bi-exclamation-triangle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 5zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
        </svg>
        <h2 class="mb-0 ml-2">Erro ao cadastrar</h2>
      </div>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <hr>
      <% proponent.errors.full_messages.each do |message| %>
        <p class="mb-0"><%= message.html_safe %></p>
      <% end %>
    </div>
  <% end %>

  <div class="card mb-2">
    <div class="card-body">
      <h5 class="card-title">Dados Pessoais</h5>
      <div class="form-row">
        <div class="col-8">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control form-control-sm" %>
          </div>
        </div>

        <div class="col-4">
          <div class="form-group">
            <%= form.label :cpf %>
            <%= form.text_field :cpf, class: "form-control form-control-sm", data: { mask: "cpf" }, maxlength: 14 %>
          </div>
        </div>
      </div>

      <div class="form-row">
        <div class="col-4">
          <div class="form-group">
            <%= form.label :date_birth %>
            <%= form.text_field :date_birth, value: (@proponent.date_birth.strftime("%d/%m/%Y") if !@proponent.date_birth.nil?), maxlength: 10, class: "form-control form-control-sm js-dateformat" %>
          </div>
        </div>

        <div class="col-4">
          <div class="form-group">
            <%= form.label :salary %>
            <%= form.text_field :salary, value: number_to_currency((params[:proponent].nil? ? form.object.salary : params[:proponent][:salary]), unit: "", separator: ",", delimiter: "."), class: "form-control form-control-sm js-salary" %>
          </div>
        </div>

        <div class="col-2">
          <div class="form-group">
            <br/>
            <button type="button" class="btn btn-outline-primary btn-sm btn-block mt-2 js-calculate">Calcular Desconto</button>
          </div>
        </div>
        <div class="col-2">
          <div class="form-group">
            <%= form.label :discount %>
            <%= form.text_field :discount, value: number_to_currency((params[:proponent].nil? ? form.object.discount : params[:proponent][:discount]), unit: "", separator: ",", delimiter: "."), readonly: true, class: "form-control form-control-sm js-discount" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="col-8">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Endereço</h5>
          <%= form.fields :address do |address| %>
            <%= render 'address_fields', f: address %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">Contatos</h5>
          <div id="telephones">
            <%= form.fields_for :telephones do |telephone| %>
              <%= render 'telephone_fields', f: telephone %>
            <% end %>

            <div class="links">
              <%= link_to_add_association "Adicionar".html_safe, form, :telephones, class: "btn btn-sm btn-outline-success" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions mt-4 mb-4">
    <%= button_tag(class: "btn btn-success btn-sm") do %>
      <i class="far fa-save"></i> <%= proponent.new_record? ? 'Cadastrar' : 'Atualizar' %>
    <% end %>
    <%= link_to "<i class='fa fa-ban'></i> Voltar".html_safe, proponents_path, class: "btn btn-light btn-sm shadow-sm" %>
  </div>
<% end %>

app/views/proponents/_telephone_fields.html.erb
<div class="nested-fields">
  <div class="form-row">
    <div class="col">
      <div class="form-group">
        <%= f.text_field :value, class: "form-control form-control-sm", data: { mask: "telephone" }, maxlength: 15 %>
      </div>
    </div>

    <div class="col-6">
      <div class="btn-group btn-group-toggle btn-block" data-toggle="buttons">
        <% Contact::KINDS.each do |n| %>
          <label class="btn btn-sm btn-outline-primary">
              <%= f.radio_button :kind, n[:id] %><%= n[:description] %>
          </label>
        <% end %>
      </div>
    </div>

    <div class="col-1">
      <%= link_to_remove_association "<svg width='1em' height='1em' viewBox='0 0 16 16' class='bi bi-trash-fill' fill='currentColor' xmlns='http://www.w3.org/2000/svg'>
        <path fill-rule='evenodd' d='M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z'/>
        </svg>".html_safe, f, class: "btn btn-sm btn-outline-danger" %>
    </div>
  </div>
</div>

app/views/proponents/edit.html.erb
<h1 class="h4 mb-4 text-gray-800 text-uppercase"><%= t('views.proponents.edit') %></h1>

<hr/>

<%= render 'form', proponent: @proponent %>

app/views/proponents/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between form-row mb-4">
  <div class="col-8">
    <h1 class="h4 mb-0 text-gray-800 text-uppercase"><%= t('views.proponents.new') %></h1>
  </div>
  <div class="col-4 text-right">
    <%= link_to t('views.proponents.new'), new_proponent_path, class: "btn btn-sm btn-outline-success shadow-sm col-4" %>
  </div>
</div>

<hr/>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= t('activerecord.attributes.proponent.name') %></th>
      <th scope="col"><%= t('activerecord.attributes.proponent.cpf') %></th>
      <th scope="col"><%= t('activerecord.attributes.proponent.date_birth') %></th>
      <th scope="col"><%= t('activerecord.attributes.proponent.salary') %></th>
      <th scope="col"><%= t('activerecord.attributes.proponent.discount') %></th>
      <th colspan="3"></th>
    </tr>
    </tr>
  </thead>
  <tbody>
    <% @proponents.each_with_index do |proponent, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= proponent.name %></td>
        <td><%= proponent.cpf %></td>
        <td><%= l proponent.date_birth %></td>
        <td><%= number_to_currency(proponent.salary, unit: "R$", separator: ",", delimiter: ".") %></td>
        <td><%= number_to_currency(proponent.discount, unit: "R$", separator: ",", delimiter: ".") %></td>
        <td class="d-flex justify-content-end">
          <div class="btn-group">
            <%= link_to t('views.show'), proponent, class: "btn btn-sm btn-outline-primary shadow-sm" %>
            <%= link_to t('views.edit'), edit_proponent_path(proponent), class: "btn btn-sm btn-outline-secondary shadow-sm" %>
            <%= link_to t('views.destroy'), proponent, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class: "btn btn-sm btn-outline-danger shadow-sm" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/proponents/new.html.erb
<h1 class="h4 mb-4 text-gray-800 text-uppercase"><%= t('views.proponents.new') %></h1>

<hr/>

<%= render 'form', proponent: @proponent %>

app/views/proponents/show.html.erb
<div class="d-sm-flex align-items-center justify-content-between form-row mb-4">
  <div class="col-8">
    <h1 class="h4 mb-0 text-gray-800 text-uppercase"><%= t('views.proponents.show') %></h1>
  </div>
  <div class="col-4 text-right">
    <%= link_to t('views.back'), proponents_path, class: "btn btn-sm btn-light shadow-sm col-3" %>
    <%= link_to t('views.edit'), edit_proponent_path(@proponent), class: "btn btn-sm btn-secondary shadow-sm ml-2 col-3" %>
  </div>
</div>

<hr/>

<div class="card mb-2">
  <div class="card-body">
    <h5 class="card-title">Dados Pessoais</h5>
    <div class="form-row">
      <div class="col-6">
        <div class="form-group">
          <label class="font-weight-bold"><%= t('activerecord.attributes.proponent.name') %></label>
          <div class="col-form-label col-form-label-sm"><%= @proponent.name %></div>
        </div>
      </div>

      <div class="col-3">
        <div class="form-group">
          <label class="font-weight-bold"><%= t('activerecord.attributes.proponent.cpf') %></label>
          <div class="col-form-label col-form-label-sm"><%= @proponent.cpf %></div>
        </div>
      </div>

      <div class="col-3">
        <div class="form-group">
          <label class="font-weight-bold"><%= t('activerecord.attributes.proponent.date_birth') %></label>
          <div class="col-form-label col-form-label-sm"><%= l @proponent.date_birth %></div>
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="col-3">
        <div class="form-group">
          <label class="font-weight-bold"><%= t('activerecord.attributes.proponent.salary') %></label>
          <div class="col-form-label col-form-label-sm"><%= number_to_currency(@proponent.salary, unit: "R$", separator: ",", delimiter: ".") %></div>
        </div>
      </div>

      <div class="col-3">
        <div class="form-group">
          <label class="font-weight-bold"><%= t('activerecord.attributes.proponent.discount') %></label>
          <div class="col-form-label col-form-label-sm"><%= number_to_currency(@proponent.discount, unit: "R$", separator: ",", delimiter: ".") %></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="form-row">
  <div class="col-8">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Endereço</h5>
        <div class="form-row">
          <div class="col-4">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.state') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.city.state.name %></div>
            </div>
          </div>

          <div class="col-4">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.city') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.city.name %></div>
            </div>
          </div>

          <div class="col-4">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.cep') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.cep %></div>
            </div>
          </div>
        </div>

        <div class="form-row">
          <div class="col-8">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.public_place') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.public_place %></div>
            </div>
          </div>

          <div class="col-4">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.number') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.number %></div>
            </div>
          </div>
        </div>

        <div class="form-row">
          <div class="col-12">
            <div class="form-group">
              <label class="font-weight-bold"><%= t('activerecord.attributes.address.neighborhood') %></label>
              <div class="col-form-label col-form-label-sm"><%= @proponent.address.neighborhood %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-4">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title">Contatos</h5>
        <table class="table table-sm table-striped">
          <thead>
            <tr>
              <th scope="col"><%= t('activerecord.attributes.telephones.value') %></th>
              <th scope="col"><%= t('activerecord.attributes.telephones.kind') %></th>
            </tr>
          </thead>
          <tbody>
            <% if @proponent.telephones.each do |telephone| %>
              <tr>
                <td class="col-form-label col-form-label-sm">
                  <i class='text-info h6'></i> <%= telephone.value %>
                </td>
                <td class="col-form-label col-form-label-sm">
                  <i class='text-info h6'></i> <%= Contact.get_human_kinds(telephone.kind) %>
                </td>
              </tr>
            <% end.empty? %>
              <tr>
                <td class="col-form-label col-form-label-sm">
                  Nenhum telefone cadastrado.
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
      </div>
    </div>
  </div>
</div>